/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as UserIndexImport } from './routes/user/index';
import { Route as SignInIndexImport } from './routes/sign-in/index';
import { Route as BooksIndexImport } from './routes/books/index';
import { Route as AdminIndexImport } from './routes/admin/index';
import { Route as BooksBookIdImport } from './routes/books/$bookId';
import { Route as UserMystatsIndexImport } from './routes/user/my_stats/index';
import { Route as UserMybooksIndexImport } from './routes/user/my_books/index';
import { Route as AdminRentalsIndexImport } from './routes/admin/rentals/index';
import { Route as AdminLogsIndexImport } from './routes/admin/logs/index';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const UserIndexRoute = UserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any);

const SignInIndexRoute = SignInIndexImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any);

const BooksIndexRoute = BooksIndexImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRoute,
} as any);

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any);

const BooksBookIdRoute = BooksBookIdImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any);

const UserMystatsIndexRoute = UserMystatsIndexImport.update({
  id: '/user/my_stats/',
  path: '/user/my_stats/',
  getParentRoute: () => rootRoute,
} as any);

const UserMybooksIndexRoute = UserMybooksIndexImport.update({
  id: '/user/my_books/',
  path: '/user/my_books/',
  getParentRoute: () => rootRoute,
} as any);

const AdminRentalsIndexRoute = AdminRentalsIndexImport.update({
  id: '/admin/rentals/',
  path: '/admin/rentals/',
  getParentRoute: () => rootRoute,
} as any);

const AdminLogsIndexRoute = AdminLogsIndexImport.update({
  id: '/admin/logs/',
  path: '/admin/logs/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/books/$bookId': {
      id: '/books/$bookId';
      path: '/books/$bookId';
      fullPath: '/books/$bookId';
      preLoaderRoute: typeof BooksBookIdImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/books/': {
      id: '/books/';
      path: '/books';
      fullPath: '/books';
      preLoaderRoute: typeof BooksIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/sign-in/': {
      id: '/sign-in/';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof SignInIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/user/': {
      id: '/user/';
      path: '/user';
      fullPath: '/user';
      preLoaderRoute: typeof UserIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/logs/': {
      id: '/admin/logs/';
      path: '/admin/logs';
      fullPath: '/admin/logs';
      preLoaderRoute: typeof AdminLogsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/rentals/': {
      id: '/admin/rentals/';
      path: '/admin/rentals';
      fullPath: '/admin/rentals';
      preLoaderRoute: typeof AdminRentalsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/user/my_books/': {
      id: '/user/my_books/';
      path: '/user/my_books';
      fullPath: '/user/my_books';
      preLoaderRoute: typeof UserMybooksIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/user/my_stats/': {
      id: '/user/my_stats/';
      path: '/user/my_stats';
      fullPath: '/user/my_stats';
      preLoaderRoute: typeof UserMystatsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/books/$bookId': typeof BooksBookIdRoute;
  '/admin': typeof AdminIndexRoute;
  '/books': typeof BooksIndexRoute;
  '/sign-in': typeof SignInIndexRoute;
  '/user': typeof UserIndexRoute;
  '/admin/logs': typeof AdminLogsIndexRoute;
  '/admin/rentals': typeof AdminRentalsIndexRoute;
  '/user/my_books': typeof UserMybooksIndexRoute;
  '/user/my_stats': typeof UserMystatsIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/books/$bookId': typeof BooksBookIdRoute;
  '/admin': typeof AdminIndexRoute;
  '/books': typeof BooksIndexRoute;
  '/sign-in': typeof SignInIndexRoute;
  '/user': typeof UserIndexRoute;
  '/admin/logs': typeof AdminLogsIndexRoute;
  '/admin/rentals': typeof AdminRentalsIndexRoute;
  '/user/my_books': typeof UserMybooksIndexRoute;
  '/user/my_stats': typeof UserMystatsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/books/$bookId': typeof BooksBookIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/books/': typeof BooksIndexRoute;
  '/sign-in/': typeof SignInIndexRoute;
  '/user/': typeof UserIndexRoute;
  '/admin/logs/': typeof AdminLogsIndexRoute;
  '/admin/rentals/': typeof AdminRentalsIndexRoute;
  '/user/my_books/': typeof UserMybooksIndexRoute;
  '/user/my_stats/': typeof UserMystatsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/books/$bookId'
    | '/admin'
    | '/books'
    | '/sign-in'
    | '/user'
    | '/admin/logs'
    | '/admin/rentals'
    | '/user/my_books'
    | '/user/my_stats';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/books/$bookId'
    | '/admin'
    | '/books'
    | '/sign-in'
    | '/user'
    | '/admin/logs'
    | '/admin/rentals'
    | '/user/my_books'
    | '/user/my_stats';
  id:
    | '__root__'
    | '/'
    | '/books/$bookId'
    | '/admin/'
    | '/books/'
    | '/sign-in/'
    | '/user/'
    | '/admin/logs/'
    | '/admin/rentals/'
    | '/user/my_books/'
    | '/user/my_stats/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BooksBookIdRoute: typeof BooksBookIdRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  BooksIndexRoute: typeof BooksIndexRoute;
  SignInIndexRoute: typeof SignInIndexRoute;
  UserIndexRoute: typeof UserIndexRoute;
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute;
  AdminRentalsIndexRoute: typeof AdminRentalsIndexRoute;
  UserMybooksIndexRoute: typeof UserMybooksIndexRoute;
  UserMystatsIndexRoute: typeof UserMystatsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  UserIndexRoute: UserIndexRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminRentalsIndexRoute: AdminRentalsIndexRoute,
  UserMybooksIndexRoute: UserMybooksIndexRoute,
  UserMystatsIndexRoute: UserMystatsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books/$bookId",
        "/admin/",
        "/books/",
        "/sign-in/",
        "/user/",
        "/admin/logs/",
        "/admin/rentals/",
        "/user/my_books/",
        "/user/my_stats/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books/$bookId": {
      "filePath": "books/$bookId.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/books/": {
      "filePath": "books/index.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.tsx"
    },
    "/user/": {
      "filePath": "user/index.tsx"
    },
    "/admin/logs/": {
      "filePath": "admin/logs/index.tsx"
    },
    "/admin/rentals/": {
      "filePath": "admin/rentals/index.tsx"
    },
    "/user/my_books/": {
      "filePath": "user/my_books/index.tsx"
    },
    "/user/my_stats/": {
      "filePath": "user/my_stats/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
